### ISSUE TITLE
Display Settings of Captcha Setup Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#10]
Hi Ajay,

Here are the tasks for you for Display Settings of Captcha Setup Page/Screen.

• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toaster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed

Regards
Sonal
Team Leader

**Comment by tech-prodigy3** [comment]
# changed files:
1.  lib/action-library.php
2. views/display-setting.php
3. inlcude/footer.php

# issues fixed:
1. read all default data from the database
2. all data updated to database
3. toaster notification shown after updating the data
4. loader works properly and refreshes all data
5.  all the fields are sanitized properly before updating them to the database.

note: appropriate issues are fixed 

checked by : 
 sonal wadhwa

ajay singh
