### ISSUE TITLE
Email Management Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#11]
Hi Sonali,

Here are the tasks for you for the Email Management Page/Screen.

• By clicking on Save Changes button all the following steps should be completed-
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Validate the fields marked with a star.
• Use encoded strings in textboxes and text area,so that it can accept string as well as special characters too.
• In case of Mailer Type drop down,if first option i.e "Send Email via SMTP" is chosen then all the fields will be shown and if second option i.e "Use PHP mail() function" is chosen then only three fields will be shown-Return Path,Word Wrap and Return Email.
• In case of Authentication drop down,if first option i.e "Use SMTP Authentication " is chosen then two fields i.e SMTP User and SMTP Password will be shown and if second option i.e "Dont Use SMTP Authentication" is chosen then these two fields will not be shown.
• In case of Return Path drop down,if Enable is chosen then Return Email field will be shown and if disable is chosen then this field will not be shown.
• Please make sure that there should be default values in drop down list.It should not be empty by default.
• Toaster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with WP-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy10** [comment]
closed #11
