### ISSUE TITLE
Licensing Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/captcha-master#13]
Hi Harpreet,

Here are the tasks for you for Licensing Page/Screen.

• Special char Validation should be checked on API KEY :  field.
•       After clicking on Validate License button, Licensing Page should redirect to current page only.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and   needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy6** [comment]
Changed Files:

 1 includes/footer.php
 2 lib/action-library.php
 3 views/captcha-master/licensing/licensing.php

  Issues Fixed:
1. Page read all the default data from the database.
   2 Special char Validation on API KEY : field.
2. Page updates all values to meta table.
3. Toster notification shown after click on save setting
4. Loader Works properly and refreshes the page after the update.
5. All the feilds are sanitized properly.

Tested By
prinkya 

changed by 
harpreet kaur
