### ISSUE TITLE
Live Traffic of logs Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#14]
Hi Inderpreet,

Here are the tasks for you for Live Traffic of logs Page/Screen-

• Please make sure that the map works properly.
• Default location of map should be set.
• Use date-pickers for the Start date and End date.
• Start date should not be greater than the End date.
• Use oTable for the Table of Recent Login Logs.
• Please make sure that the roles and capabilities along with WP-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy17** [comment]
Closed  #14
