### ISSUE TITLE
Live Traffic of Logs Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#15]
Hi Shilpa,

Here are the tasks for you for Live Traffic of Logs Page/Screen-

• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• By clicking on Apply Button all the selected data should be deleted and proper Alerts should be used while deleting the data.
•In Action column ,Use an icon icon -trash and after clicking on this icon,the particular row should be deleted.
• Loader Works properly and refreshes the page.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with WP-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy7** [comment]
Issue ID: #15 changes made at 11.00 AM 

Changed Files: 
1. includes\footer.php
2. lib\action-library.php
3. includes\queries.php
4. views\logs\live-traffic.php

Issues Fixed:
1. By clicking on Apply Button all the selected data sre deleted and proper Alerts are used while deleting the data
2. Data displays on the screen in respective columns.
3. Loader Works properly.
4. Fields are being sanitized properly
5. WP-nonces are created.
6. Loader Works properly.

Note: All issues are fixed so this ticket is marked as closed.

Changed By : Shilpa Rana

Tested By :  Sonal Wadhwa
