### ISSUE TITLE
Blocking  IP Address for "Manage IP Addresses" and "Manage IP Ranges" Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/captcha-master#17]
Hi Manpreet,

Here are the tasks for you for Manage IP Addresses and Manage IP Ranges Page/Screen.

Manage IP Addresses Page:

• After clicking on "Block IP Address" button, IP Address should get blocked which is mentioned on "Manage IP Addresses" Page. 
• Blocking time period we can consider from "Blocked For" field. 

Manage IP Ranges Page:

• After clicking on "Block IP Address Range" button, IP Address should get blocked if that IP Address comes between Start and End IP Range.
• Blocking time period we can consider from "Blocked For" field. 

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy11** [comment]
Closed #17

Bug ID/Issue ID: #17 Changes Made at 2015-07-30 6:00PM

# Changed Files: 
1. captcha-master.php

# Issues Fixed:
1. Function(block_ip_address_captcha_master) For Blocking IP Address.
2. Hook for The Function(block_ip_address_captcha_master).
3. Function(getIpAddress) For getting of The System IP Address.

Note: All Issues are Fixed

# Changed By : 

Manpreet Singh

# Tested By:

Priyanka
