### ISSUE TITLE
 Unblocking IP Address for "Manage IP Addresses" and "Manage IP Ranges" Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/captcha-master#18]
Hi Manpreet,

Here are the tasks for you for Manage IP Addresses and Manage IP Ranges Page/Screen.

Manage IP Addresses and Manage IP Ranges Page:

•  Once blocked time period time period is over that IP Address should get Unblocked.
•  Location of an IP Address should show.
•  "Blocked Date & Time" and 'Release Date & Time" field should be there. 

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy11** [comment]
Bug ID/Issue ID: #18

# Changed Files: 
1. view/advance-security/manage-ip-addresses.php
2. view/advance-security/manage-ip-ranges.php
3. lib/action-library.php
4. captcha-master.php
5. lib/unblock-script.php

# Issues Fixed:
1. Blocked Date & Time and Release Date & Time in manage-ip-addresses.php and manage-ip-ranges.php
2. Binding Location in action library from cpo_get_ip_location_captcha_master() function.
3. cpo_get_ip_location_captcha_master.php function in captcha-master.php.
4. Scheduler function wp_schedule_captcha_master in captcha-master.php .
5. Unschedule function wp_captcha_master_cron_unblock_schedule in captcha-master.php . 
6. unblock_script_captcha_master function for including unblock-script.php .
7. add_filter hook for wp_captcha_master_cron_unblock_schedule.
8. wp_captcha_master_cron_unblock_schedule function for cron schedules.
9. create new page in lib unblock-script.php .
10. unblocking ip address code in unblock-script.

Note: Reported issues are Fixed.

# Changed By : 

Manpreet Singh
