### ISSUE TITLE
 Blocking Options of Advance Security  Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/captcha-master#3]
Hi Sandeep,

Here are the tasks for you for the  Blocking Options of Advance Security  Page/Screen.

• Please make sure that the page properly updates all the blocking options to the meta tables.
• "Maximum Login attempt in a Day :" should accept only digits. 
• If Auto Remove Blocked Entries :  is Enable then only "Remove Blocked Entries Of Day" option should show below.
• Day range should show upto 31 days in "Remove Blocked Entries Of Day" dropdown list.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy2** [comment]
Hi Sandeep,

Please recheck your issue detail.

**Comment by tech-prodigy4** [comment]
Issued ID: #3  Changes Made at time     

```
    Changed Files: 
    =========
    1. includes/footer.php
    2. lib/action-library.php
    3. views/advance-security/blocking-options.php

    Issues Fixed:
    =======
    1. Validations are given on text fields.
    2. All the default addresses of the meta tables has been updated successfully.
    3. Loader and toster notifications are working properly and refreshes the page after the update.
    4. Page updates all values to meta table
    5. All the feilds are sanitized properly
```

Note: Reported issues are fixed.So this issue is marked as closed.

```
    Changed By:

    Sandeep Kaur
```
