### ISSUE TITLE
Manage Ip Addresses of  Advance Security   Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/captcha-master#4]
Hi Manpreet,

Here are the tasks for you for the  Manage IP Address of  Advance Security   Page/Screen.

• "IP Address :" field should be a mandatory field.
• IP address should be a  valid IP Address. 
-       IP Address Duplicasy should be check to make sure that these don't exist in the database earlier.
  • "Comments :" field should accept special characters too.
  • After clicking on "Block IP address" button, data should be saved. 
          • One new entry will go in to the parent table of Captcha Master. and 4 enties will be inseted into the  meta table. 
          • Please check the meta key values of the meta table:
              ip_address
              blocked_for
              comments
                              location
              date_time 
  •  Status should be removed from this page
  •  Heading should be "View Blocked IP Address Range"
  •  Delete Icon should be there below Actions field.
  •  Only Delete option should be there in drop down field. 
  • Toster Notification should be shown when an update button is being clicked.
  • Loader Works properly and refreshes the page after the update.
  After cicking on clear button, IP address and Comments should get deleted from the controls above. 
  • Please make sure that all the fields are being sanitized properly before updating them to the database.
  • Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and   needed.

Regards
Priyanka S.
Team Leader

**Comment by tech-prodigy2** [comment]
Manpreet,

Please recheck your issue #4 detail.

Regards,
Priyanka Saloni

**Comment by tech-prodigy11** [comment]
closed #4
