### ISSUE TITLE
Install Script for Captcha Matser

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#6]
Hi Sonali,
Here are the tasks for you for the Install Script for Captcha Matser-
  We need to make sure that the install script is creating tables for the user in the database if those tables don't exists.
  Also make sure that the default entries are being added to them so that the data is being inserted into these tables.
  The following tables should be there :
  1) Main Table for Parent Records
  2) Meta Table for Child Records

Regards
Sonal
Team Leader

**Comment by tech-prodigy10** [comment]
Closed #6
