### ISSUE TITLE
Captcha Type of Captcha Setup Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#7]
Hi Priya,

Here are the tasks for you for the Captcha Type of Captcha Setup Page/Screen.
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Please make sure that the page properly updates all the default settings to the meta tables.
• In case of Text captcha ,read following points carefully-
a) Please make sure that there will be numeric values in Captcha height,Width,Lines and Noise Level fields and no strings should be entered in these fields.
b) There should be default values in drop down list.It should not be empty by default.The related drop downs are-Captcha Type,Captcha Background,Border Style,Signature Style and Signature Font.
c) Use Color-picker for Border style last field i.e textbox,Lines color,Noise color,Text shadow color and Signature Style last field i.e textbox.
d) Please make sure that there will be default color value #cccccc in above mentioned textboxes.
e) In Border Style field, First two controls will be drop down-first for the border size from 00px to 100 px and second for style and third will be a textbox for border color and default color should be #cccccc.
f) In Signature Style field, First two controls will be drop down-first for the signature size from 00px to 100 px and second for style and third will be a textbox for signature color and default color should be #cccccc.
g) In Signature Text field,use encoded strings so that it can accept string as well as special characters too.
• In case of Logical captcha ,read following points carefully-
a) Please Update all the default values of Mathematical operations in database.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy14** [comment]
Hi Priya,

Please work on above mentioned issue(#7) which was earlier assigned to Ajay.

Note: Ajay, No need to work on above mentioned issue(#7)

**Comment by tech-prodigy14** [comment]
Hi Priya,

Please recheck your issue.

Regards
Sonal
Team Leader

**Comment by tech-prodigy15** [comment]
Closed #7
