### ISSUE TITLE
Error Message of Captcha Setup Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#8]
Hi Inderpreet,

Here are the tasks for you for the Error Message of Captcha Setup Page/Screen.

• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Use encoded strings so that it can accept string as well as special characters too.
• Toster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy14** [comment]
Hi Inderpreet,

Please recheck your issue.

Regards
Sonal
Team Leader

**Comment by tech-prodigy17** [comment]
Closed #8

**Comment by tech-prodigy17** [comment]
Closed #8
