### ISSUE TITLE
Recent Login Logs of Logs Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/captcha-master#9]
Hi Shilpa,

Here are the tasks for you for Recent Login Logs of Logs Page/Screen-

• Please make sure that the map works properly.
• Default location of map should be set.
• Use date-pickers for the Start date and End date.
• Start date should not be greater than the End date.
• Use o table for the Table of Recent Login Logs.
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Loader Works properly and refreshes the page.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with WP-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy7** [comment]
Issue ID: #9 changes made at 11.00 AM 

Changed Files: 
1.  includes\footer.php
2. lib\action-library.php
3. lib\helper.php
4. includes\queries.php
5. views\logs\recent-login-logs.php

Issues Fixed:
1. Map works properly.
2. date-pickers for the Start date and End date.
3. Start date greater than the End date.
4. o table for the Table of Recent Login Logs.
5. Data displays on the screen in respective columns.
6. Loader Works properly.
7. WP-nonces are created.
8. Fields are being sanitized properly
9. Data displays in table according to start date and end date.

Note: All issues are fixed so this ticket is marked as closed.

 Changed By :Shilpa Rana
Tested By : Sonal Wadhwa
